version: '3.8'

services:
  jony-website:
    build: .
    ports:
      - "8080:8080"
    container_name: jony-performer-website
    restart: unless-stopped
    environment:
      - NODE_ENV=production

